Update html-questions.md
yangshun/front-end-interview-handbook pull request #429
Opened 2024-04-01 05:48 UTC by priyajeet-7396

Added two more questions that were missing from the page :)

2024-04-16 17:30 UTC, kdgyimah requested changes
Great addition! However you will need to enclose the HTML tags with `` for  markdown.

I have added it, so you can update it in the pull request.

2024-04-16 17:30 UTC, kdgyimah commented on contents/html-questions.md
> +<hr>: Used to create horizontal rules or separators.
`<img>`: Used to embed images into the document.

`<br>`: Used to insert line breaks or forced line breaks.

`<hr>`: Used to create horizontal rules or separators.

2024-04-18 17:26 UTC, pietrop commented on contents/html-questions.md
> +<hr>: Used to create horizontal rules or separators.
```suggestion
`<img>`: Used to embed images into the document.
`<br>`: Used to insert line breaks or forced line breaks.
`<hr>`: Used to create horizontal rules or separators.
```

2024-06-01 06:29 UTC, yangshun approved these changes

2024-06-01 06:32 UTC, merged